### PR TITLE
Success page 

### PR DESCRIPTION
**Pull request by bion**

### CODE REVIEW

**Comment by philipbjorge** [comment]
@bion How should I test this without sending a message to a superdelegate?
Is that possible right now without a proxy like fiddler or charles?

**Comment by philipbjorge** [comment]
@bion -- How am I supposed to test this?

Specifically, I went into SendMessage and added an early return so no jobs got queued to send messages to delegates (Do I need to do this?)

After that, I got a NetConnectNotAllowedError from WebMock when trying to verify the recaptcha. What's the recommended approach to bypassing/stubbing this?

**Comment by dbalatero** [comment]
@philipbjorge 

> Specifically, I went into SendMessage and added an early return so no jobs got queued to send messages to delegates (Do I need to do this?)

No, just avoid running `rake jobs:work` - as long as you don't run a worker, you won't pull jobs out of the queue.

We could add a `return if Rails.env.development?` in the SendMessage worker as well, if we just want to wholesale block sending messages while in development (`Rails.env.test?` will still work for the purpose of recording 1 VCR cassette)

> After that, I got a NetConnectNotAllowedError from WebMock when trying to verify the recaptcha. What's the recommended approach to bypassing/stubbing this?

WebMock should only be active in RSpec, so assuming you're running a test… if the network request is instantiated from the server-side, you can wrap the test in a `VCR.use_cassette("path/to/cassette") { ... }` block.

If it's client-side JS, we'll have to Google that…

It's possible that this is happening:

* client-side Recaptcha is actually hitting a network resource for real, and getting new data
* the server gets the new Recaptcha data, and since the `params` are different (a new captcha = new tokens/params/etc), it fires a request to recaptcha with different params. VCR does url, method, params matching to find a replayable web request. If there's already a cassette in use AND it doesn't match a request, it will raise an error.

If this is the case (we need to verify ^) then we either need to:

* mock out the client-side JS call in some easy way (Capybara might expose a fake server for this)
* directly stub out the recaptcha verification
* loosen the pattern matching that VCR uses to match cassettes

**Comment by bion** [comment]
@dbalatero @philipbjorge why have vcr and webmock running in development mode at all? aren't they only for testing?

**Pull request merged**
